### ISSUE TITLE
Bottom Navigation View

### ISSUE THREAD

**Issue by KeyDutch** [andkulikov/Transitions-Everywhere#104]
Здравствуйте. Возможно ли сделать такие переходы с помощью вашей библиотеки? Если да, не могли бы примерно подсказать как? Спасибо.
![Screenrecorder-2020-08-18-02-13-12-22](https://user-images.githubusercontent.com/45684943/90449498-a56b3800-e0f8-11ea-9b3c-ccca7c5811de.gif)

**Comment by andkulikov** [comment]
Здравствуйте. На самом деле этот эффект выглядит довольно кастомным и скорее всего проще его будет достигнуть создав кастомную Вью и рисовать все вручную на Canvas с помощью аниматоров. Не думаю что эта библиотека чем то поможет в этой задаче

**Comment by KeyDutch** [comment]
Спасибо за ответ.
