### ISSUE TITLE
Alpha values not being respected in scenes

### ISSUE THREAD

**Issue by schwiz** [andkulikov/transitions-everywhere#12]
Hello thanks for this backport! I have however found an issue where it isn't not playing nicely with another widget library. 

I have a sample project here demonstrating the issue. If you compile and run the project and click the add payment method button the Transition will kick in displaying a new scene. If android:ids are shared between scenes then it looks as if the alpha values are not honored.  Switching the Transition package names back to the framework will resolve the issue.

Here is the sample project
https://drive.google.com/file/d/0B9BQRk_YVoNrdDVqVVduY3dnY0k/view?usp=sharing

And here is a link to the issue originally opened on the widget library.
https://github.com/IanGClifton/AndroidFloatLabel/issues/20

**Comment by andkulikov** [comment]
Hello. Thanks for information. I will fix it soon.
Strange, but this issue does not reproduced on 4.4/

**Comment by schwiz** [comment]
I'm seeing this on GS5 running Lollipop. Haven't tested on other devices/versions.

**Comment by andkulikov** [comment]
on nexus 5 with 5.0 its work incorrectly too

**Comment by schwiz** [comment]
Okay good so you are able to see the issue then? Looks like its a 5.0 only issue?

**Comment by andkulikov** [comment]
yes, i think so. i will try to debug)

**Comment by andkulikov** [comment]
you found a really major bug, thanks!
i fixed it and will upload new version on maven soon

**Comment by c0nnector** [comment]
@andkulikov Please update soon :)

**Comment by c0nnector** [comment]
@andkulikov Not sure if the same issue, but TransitionManager.beginDelayedTransition() messes with the alpha values as well. I used both the maven version and the one with the issue fix #12

It works with the native api. Also, tried in android 4.4.4 & 5.0

Made a simple example that demonstrates the issue https://github.com/c0nnector/TransitionsIssue

**Comment by andkulikov** [comment]
c0nnector, thanks!

both of these bugs already fixed in new version 1.3.0

**Comment by c0nnector** [comment]
@andkulikov Awesome! Great lib :+1:
