### ISSUE TITLE
Targets of a Transition is not removed while using removeTarget (int targetId)

### ISSUE THREAD

**Issue by Avinash-Bhat** [andkulikov/transitions-everywhere#15]
Consider the following code:

     Transition transition = ...;

     transition.addTarget(R.id.my_view);

     ...

     transition.removeTarget(R.id.my_view);

It is apparent from the [documentation](https://github.com/andkulikov/transitions-everywhere/blob/master/library/src/main/java/android/transitions/everywhere/Transition.java#L1061) that the call to `Transition.removeTarget(int)` should remove the view with id `R.id.my_view` being included in further transitions. But instead the following error will be shown:

     Caused by: java.lang.IndexOutOfBoundsException: Invalid index <some-random-int>, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.remove(ArrayList.java:403)

this is because the implementation is calling ArrayList.remove(int) instead of ArrayList.remove(Object).

*PS: the upstream bug is at http://b.android.com/167061 or [here](https://github.com/android/platform_frameworks_base/issues/62)*

**Comment by andkulikov** [comment]
thanks. i wiil check it

**Comment by Avinash-Bhat** [comment]
@andkulikov, check the PR.

I think this will be the best way of fixing this issue.

**Comment by Avinash-Bhat** [comment]
@andkulikov any idea when this will be available in maven/bintray?

**Comment by andkulikov** [comment]
@Avinash-Bhat I think within two days. I want to fix one other issue

**Comment by andkulikov** [comment]
this fix already in maven with version 1.3.2

**Comment by Avinash-Bhat** [comment]
+1, thanks
