### ISSUE TITLE
Cannot apply interpolator

### ISSUE THREAD

**Issue by ealymbaev** [andkulikov/transitions-everywhere#18]
I cannot apply interpolator in the xml, as well as in the code.

I tried using the following code:

```
    <transitionSet
        app:interpolator="@android:interpolator/decelerate_quad"
        >
```

But that does not seem to have effect.

**Comment by andkulikov** [comment]
fixed in 1.3.2. for now you can specify interpolator for all transitionSet and it will apply to all child transitions (android framework transitions doesn't have this possibility)
