### ISSUE TITLE
Why not support animations pre 3.0

### ISSUE THREAD

**Issue by Mukul-Sharma** [andkulikov/Transitions-Everywhere#20]
Animations can be supported pre 3.0 using ViewCompat in support library.

**Comment by andkulikov** [comment]
ViewCompat actually doesn't contain any backports for Animations Framework from 3.0. It could be backported with https://github.com/JakeWharton/NineOldAndroids but i don't see any reasons for this:
- all exists devices with 2.x is really slow. all animations on this devices will looks terrible and laggy
- Android 2.x is too old. there is no real reasons to develop applications with lower min sdk version than 14 for now. percent of users with such devices is to small and will decrease every month
So why do we need to waste our time trying to backport animations for pre 3.0?
