### ISSUE TITLE
Slide left and right do not work

### ISSUE THREAD

**Issue by tntnt** [andkulikov/Transitions-Everywhere#23]
Slide always goes to bottom (or top

**Comment by andkulikov** [comment]
its not true!)
can you provide example of incorrect working code, please?

**Comment by tntnt** [comment]
andrey,

attached is a project. use the menu to run an xml transition or a coded 
transition.

terry

**Comment by andkulikov** [comment]
attaches not working this way, its just github comments. please send me your files to andkulikov@gmail.com

**Comment by andkulikov** [comment]
just modify your slide.xml this way
```
<?xml version="1.0" encoding="utf-8"?>
<transitionSet
	xmlns:app="http://schemas.android.com/apk/res-auto"
	app:transitionOrdering="together">
	<slide
		app:duration="350"
		app:slideEdge="left">
		<targets>
			<target app:targetId="@+id/hello" />
		</targets>
	</slide>
	<slide
		app:duration="350"
		app:slideEdge="right">
		<targets>
			<target app:targetId="@+id/goodbye" />
		</targets>
	</slide>
</transitionSet>
```
after that xml inflated transition and created by code one will works the same

you should use "app" prefix instead of "android" as i mentioned in readme:
https://github.com/andkulikov/Transitions-Everywhere#transitions-via-xml
