### ISSUE TITLE
Is there any tricks to make transitions with shared elements?

### ISSUE THREAD

**Issue by evasyuk** [andkulikov/Transitions-Everywhere#24]
As far as I understood transitions with shared elements applying at Activity, which means that standard methods such as "setSharedElementReturnTransition(Transition transition)" and "setExitTransition(Transition transition)" couldn't be applied and I need to create some custom activity with overridden Transitions framework processing in order to use your TransitionsEverywhere library? Am I right or have I missed something?

**Comment by andkulikov** [comment]
My transitions are cannot be compatible with android activity transitions unfortunately. Now I don't have a plan for porting similar api, but maybe someday i will try it.
It's not so simple to override transition framework processing in activity. For now you can use one activity and animate scene changes inside it.
