### ISSUE TITLE
Fade transition displays its target views above targets of other transitions.

### ISSUE THREAD

**Issue by urandom** [andkulikov/Transitions-Everywhere#29]
Hi,

When I try to run a fade transition, and the equavalent of a 'move' transition in the same set, the fading elements always appear above the elements that move. Transition order or target view z order doesn't seem to matter at all. I've observed this behavior in both api v16 and v23.

Is there any way to enforce some kind of z-ordering for views of these transitions?

**Comment by andkulikov** [comment]
Hello. Unfortunately it can`t be configured. Fade transition actually animate screenshot of view in overlay of scene layout and becouse of it fading elements always appear above. Why it animated screenshot but not view itself - view doesnt exist in layout in second scene, it already removed from layout.

**Comment by urandom** [comment]
Would it be possible to somehow define where the view overlay should be inserted? Then we might be able to specify the container view as the parent of the overlay, and tell it to be added as the first child, thus it would appear below any other transition.

**Comment by andkulikov** [comment]
for now it cant be configured. overlay can be only above all container. just because it is overlay, not real child of layout. but if view will exist in second scene that will be animated alpha of view itself, not copy of it in overlay. for example you should change visibility of view to GONE or INVISIBLE instead of removing it from layout. if you show me your code I can help you with it

**Comment by blackbbc** [comment]
Hi. I find out that scale animation also displays at its target views above targets of other transitions.
When using fading transition, I can solve it by adding the view of the same id in the second scene and set it as gone or visible. But if I do the same thing, the scale transition won't show. Do you have any ideas?

**Comment by blackbbc** [comment]
Oh my god! Finally I solve it. They must have the same layout. Not only the view it self but also the viewgroup.

**Comment by andkulikov** [comment]
Hi. 
Yeah, there are two possible way hot to perform visibility change transition. When it safe to use view itself(in your case it when they are in the same layout) and when instead of view screenshot of view is animating in overlay.
