### ISSUE TITLE
Crash on Android 4.1 with transitions inside toolbar

### ISSUE THREAD

**Issue by stepango** [andkulikov/Transitions-Everywhere#30]
*TransitionManager.beginDelayedTransition(getToolbar());*

If i'll call this code before expandActionView in any item in toolbar all toolbar content will be messed up.

If toolbar has animateLayoutStateChanges flag equals true any toolbar interaction would cause a crash in this situation.

**Comment by andkulikov** [comment]
fixed in 1.6.1. thanks!
