### ISSUE TITLE
Transition for new ListView Items

### ISSUE THREAD

**Issue by troy21688** [andkulikov/Transitions-Everywhere#34]
I am trying to add a transition for every ListView item that gets added. My idea is to incorporate the transition code before I call notifyDataSetChanged(). Here is my code:

     mUpdateComments = new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                mNumberOfCommentsAtPoll = (int) dataSnapshot.getChildrenCount();
                for (DataSnapshot x : dataSnapshot.child(COMMENTS_LABEL).getChildren()) {
                    Log.v("DATA_SNAPSHOT", x.toString());
                    if (mCommentIDArrayList.contains(x.getKey())){
                        Log.v("Comment_Already_Added", x.getKey());
                    } else {
                        Log.v("Child_Added_Called", "Child Added Called");
                        mCommentIDArrayList.add(x.getKey());
                        String commentID = (String) dataSnapshot.child(COMMENTS_LABEL).child(x.getKey()).child("COMMENT").getValue();
                        Log.v("New_Comment", "The new comment is " + commentID);
                        String userID = (String) dataSnapshot.child(COMMENTS_LABEL).child(x.getKey()).child("USER_ID").getValue();
                        Log.v("New_User_ID", "The new userID is " + userID);
                        mCommentArrayList.add(new Comments(mUserAvatar, userID, commentID));
                        Collections.reverse(mCommentArrayList);
                        mCommentAdapter.notifyDataSetChanged();
                    }
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {

            }
        };

**Comment by andkulikov** [comment]
And its not working? Where your TransitionManager.beginDelayedTransition call?
Actually I can recommend you to use RecyclerView with build-in item animators for that task.

**Comment by troy21688** [comment]
Thanks, much appreciated.

On Tue, May 24, 2016 at 10:32 AM, Andrey Kulikov <notifications@github.com>
wrote:

> And its not working? Where your TransitionManager.beginDelayedTransition
> call?
> Actually I can recommend you to use RecyclerView with build-in item
> animators for that task.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/andkulikov/Transitions-Everywhere/issues/34#issuecomment-221309828>
>



-- 
Troy Chuinard, CPA
