### ISSUE TITLE
Animating the container itself.

### ISSUE THREAD

**Issue by drivfe** [andkulikov/Transitions-Everywhere#36]
Hey, first I wanna say thank you a lot for this library.

I've been using it and it seems to me that only the children of the container ViewGroup gets animated, is there any way it could animate the container itself too? (Without needing to pass in the parent as the container to beginDelayedTransition())

Thanks

**Comment by andkulikov** [comment]
Hey, thanks!

Actually it can animate container itself. Probably except case when it the root in Activity. Can you show code with example?

**Comment by drivfe** [comment]
I just did some tests and it looks like it does animate it, but for some reason in my specific case it isn't working.

```
<ScrollView>
    <RelativeLayout>
        ...
        <LinearLayout android:visibility="gone"
            ...>
            <com.drivfe.rocketfriend.ui.views.RankView
                android:id="@+id/profile_rank_view_duel"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <com.drivfe.rocketfriend.ui.views.RankView
                android:id="@+id/profile_rank_view_doubles"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <com.drivfe.rocketfriend.ui.views.RankView
                android:id="@+id/profile_rank_view_solo_standard"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

            <com.drivfe.rocketfriend.ui.views.RankView
                android:id="@+id/profile_rank_view_standard"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </LinearLayout>
    </RelativeLayout>
</ScrollView>
```
RankView is just a RelativeLayout with some TextViews.

Relevant code snippet:
```
TransitionManager.beginDelayedTransition(ranksLayout, Utils.createEnterTransition());
ranksLayout.setVisibility(View.VISIBLE);
```
Utils.createEnterTransition() returns a TransitionSet that I use everywhere throughout the app and it works fine.
ranksLayout is the LinearLayout.

In this case the ranksLayout becomes visible instantly, no fade ins or anything. The only way I can get it to work correctly is if i do setVisibility(View.VISIBLE) to every individual RankView and make the LinearLayout visible by default.

**Comment by andkulikov** [comment]
between, try the same but when you set android:visibility="invisible" for LinearLayout before transition. so it will be animation from invisible to visible. it can make sense because actually setVisibility(View.VISIBLE) for LinearLayout can also change the size of RelativeLayout and ScrollView

**Comment by drivfe** [comment]
Yep, invisible works. Thanks.
