### ISSUE TITLE
May I translate it into Chinese

### ISSUE THREAD

**Issue by captain-miao** [andkulikov/Transitions-Everywhere#38]
That article was great! 

[Animate all the things. Transitions in Android](https://medium.com/@andkulikov/animate-all-the-things-transitions-in-android-914af5477d50)

May I translate it into Chinese??

**Comment by andkulikov** [comment]
Yes, sure!

**Comment by captain-miao** [comment]
translation for Chinese :https://yanlu.me/animate-all-the-things-transitions-in-android/

**Comment by andkulikov** [comment]
Thank you! I updated readme with the link
