### ISSUE TITLE
DataBinding compatibility

### ISSUE THREAD

**Issue by ditzdragos** [andkulikov/Transitions-Everywhere#41]
Hi,

I can't use it in activities in which I use DataBinding. Do you know anything related to this issue? I tried using different ViewGroups as the {sceenRoot}, but no success so far...
Thanks in advance!

**Comment by andkulikov** [comment]
Hello.
I've never tried Data Binding yet. Maybe you can create an example project with the issue so I will be able to take a look on it. Thank you

**Comment by httpdispatch** [comment]
This solution works well for me http://stackoverflow.com/a/36034488/527759
