### ISSUE TITLE
on Adapter  donot use  

### ISSUE THREAD

**Issue by qinyang1018** [andkulikov/Transitions-Everywhere#42]
public class UFComplexMatchControlAdapter extends RecyclerArrayAdapter<UFControlConfig> {

    public UFComplexMatchControlAdapter(Context context) {
        super(context);
    }

    @Override
    public BaseViewHolder OnCreateViewHolder(ViewGroup parent, int viewType) {
        return new ViewHolder(parent, 0);
    }

    class ViewHolder extends BaseViewHolder<UFControlConfig> {

        @Bind(R.id.fragment_complexmatch_bottom_control_name)
        TextView mFragmentComplexmatchBottomControlName;
        @Bind(R.id.transitions_container)
        AutoRelativeLayout mTransitionsContainer;

        public ViewHolder(ViewGroup parent, @LayoutRes int res) {
            super(parent, R.layout.fragment_complexmatch_bottom_control_item);
            //初始化ButterKnife
            ButterKnife.bind(this, itemView);
        }

        @Override
        public void setData(UFControlConfig data) {
            super.setData(data);
            TransitionManager.beginDelayedTransition(mTransitionsContainer, new Recolor());
            mFragmentComplexmatchBottomControlName.setTextColor(getContext().getResources().getColor(data.isSelected() ? R.color.white : R.color.black_text));
            mFragmentComplexmatchBottomControlName.setBackgroundDrawable(
                    new ColorDrawable(getContext().getResources().getColor(data.isSelected() ? R.color.black_text :
                            R.color.white)));
//            mFragmentComplexmatchBottomControlName.setBackgroundColor(getContext().getResources().getColor(data.isSelected() ? R.color.black_text : R.color.white));
//            mFragmentComplexmatchBottomControlName.setBackgroundResource(data.isSelected() ? R.drawable.stroke_button_selected : R.drawable.stroke_button);
            mFragmentComplexmatchBottomControlName.setText(data.getName());
        }
    }

}

**Comment by qinyang1018** [comment]
```
@Override
    public void controlSelected(int position) {
            if(this.controlSelected != -1){
                this.controls.get(controlSelected).setSelected(false);
            }
            this.controls.get(position).setSelected(true);
            this.controlSelected = position;
            this.controlAdapter.notifyDataSetChanged();
    }
```

**Comment by andkulikov** [comment]
Hello,

I think in your case notifyDataSetChanged will recreate ViewHolder and item view. Because of if there are nothing to animate. You can try to use it with stable ids, in that case viewholder will be reused. https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#setHasStableIds(boolean)

**Comment by qinyang1018** [comment]
i am use [EasyRecyclerView](https://github.com/Jude95/EasyRecyclerView/blob/master/README.md) it isnot recyclerview ，
I do not know how to solve
