### ISSUE TITLE
Google has backported the Transitions framework to API14

### ISSUE THREAD

**Issue by ivanfeli** [andkulikov/Transitions-Everywhere#44]
https://developer.android.com/topic/libraries/support-library/revisions.html

https://developer.android.com/reference/android/support/transition/package-summary.html

**Comment by andkulikov** [comment]
Yes, nice start for Google. 
I checked out the code and it's quite early to use it now. A lot of functionality is not backported at all. And I already can imagine different corner cases when ported ChangeBound and Fade will work incorrect before kitkat but Transitions-Everywhere's versions will proper handle it.

**Comment by Adambl4** [comment]
I wish `Transitions-Everywhere` a long life.

**Comment by rhonyabdullah** [comment]
FYI [Transitions in the Android Support Library](https://medium.com/google-developers/transitions-in-the-android-support-library-8bc86a1d688e#.xdft2mgna)

**Comment by andkulikov** [comment]
[Article about Support Library for Transitions. Overview and comparison with Transitions-Everywhere](https://medium.com/google-developers/transitions-in-the-android-support-library-8bc86a1d688e#.qnxhzly8y)

**Comment by dehghani-mehdi** [comment]
@andkulikov I'm sorry for silly question here, almost 2 years after your article on medium, so still you suggest to use your library over support library for transitions?

**Comment by andkulikov** [comment]
Hi. Support library is slowly improving, but still not so fast. I still suggest to use my library as a support one contains bugs. I am updating the article with updates for bugs

**Comment by andkulikov** [comment]
Please check out the main README file. I joined Google and fixed bugs I knew about AndroidX Transitions. I released version 2.0.0 of Transitions-Everywhere based on AndroidX transitions.
