### ISSUE TITLE
"ChangeTransform" on KITKAT 

### ISSUE THREAD

**Issue by dush999** [andkulikov/Transitions-Everywhere#46]
The following code works fine on Marshmallow (see this video https://youtu.be/1pZTlkjiHRg ), but gives strange animation on KITKAT ( https://youtu.be/m8bGYOA-Znw ) Any reason for this ? 

        ChangeBounds changeBounds = new ChangeBounds();
        ChangeTransform changeTransform = new ChangeTransform();
        Fade fadeOut = new Fade(Fade.OUT);

        transition1 = new TransitionSet();
        transition1.setOrdering(TransitionSet.ORDERING_TOGETHER);
        transition1.addTransition(changeTransform) // "changeTransform" is not working on KITKAT 
                     .addTransition(changeBounds)
                     .addTransition(fadeOut);
        transition1.setDuration(300);

**Comment by andkulikov** [comment]
Hello.
Reason is very simple - ChangeTransform is the only transition that is not backported :(
Unfortunately its hard to backport. 

Please try also ChangeBounds with setReparent(true)

**Comment by dush999** [comment]
Thanks Andrey.  setReparent(true) fixes the issue on KITKAT.
