### ISSUE TITLE
Different Results between android.transitions and TransitionsEverywhere

### ISSUE THREAD

**Issue by Gryzor** [andkulikov/Transitions-Everywhere#47]
Hi, I've been playing around with the KitKat (and above) version of the android transition framework, mainly exploring its features. I'm still relatively new when it comes to all the bells and whistles of what it can and can't do.

After creating a sample app with KitKat's framework, i decided to change import Transitions-Everywhere and simply replace the imports to compare. Let me say that the library is impressive, good work :)

Long story short, there are a few noticeable differences and I'm wondering what am I doing wrong.

First, I've created a sample project which allows you to see _the same code_ running on either framework (the code is literally a copy/paste with the imports/names changed to reflect which one is which).

It's available here: https://github.com/Gryzor/TransitionsEverywhereComparison

(Please run it on KitKat and above, I didn't add checks for the Android counterpart which obviously only works on KitKat and above).

Noticeably, if you look at `android_transition_set.xml` (and its almost identical `transition_everywhere_set.xml` counterpart), you will notice that it tries to play **together** to different targets: 

`changeBounds`
`ChangeColor`(custom transition taken from Google's samples, each version uses the corresponding framework)
`fadeIn` 
`slide` 

There are two scenes: `scene_1` and `scene_2`. They are not too fancy, just a few widgets that have a couple different properties. 

Tapping `Go` "button" will alternate between both scenes. The "Backwards" transition is just an AutoTransition (I'm only really interested in going forwards)

The code for each activity is almost identical, except for the fact that they inflate the corresponding `TransitionManager` from XML, which, in turn, points to the corresponding `TransitionSet`.

### PROBLEMS IN Transitions Everywhere 
(note, I only point problems when going from scene 1 to scene 2, the reverse is just a standard AutoTransition that I only added to make it easier to observe the first transition multiple times).

1. The  `Line Of Text Above` (red), doesn't fade in at the same time, it's as if it appears after the animations are done (?)
2. The Custom Color transition is not executed in neither view (Go button and "This is a line of Text"  (yellow/purple). 
3. The lines of text below fade out then fade in, when they shouldn't because they should only be targeted by the change bounds. All other Transitions have different/specific targets. 
4. The Slide In (I JUST SHOWED UP!) doesn't happen (it fades in together with the others).
5. The Go Text bug is unrelated to either framework as it seems to be a limitation mentioned here: https://developer.android.com/training/transitions/overview.html#Limitations (and I have no idea how to overcome that yet).

What am I missing? :)

p.s.: one guess is that the xml definitions for transitionseverywhere must be changed so instead of `<Fade>` I may have to use a different name, but I'm not sure.

**Comment by andkulikov** [comment]
Hello!

Yes, there are differences how to use xml inflation for Transitions-Everywhere. You can found an example in the article https://medium.com/@andkulikov/animate-all-the-things-transitions-in-android-914af5477d50#.f2m72p9i3 (find with "Create Transition with xml"). 
What should you do: put xml file in the anim folder and replace all "android:" tags with "app:" like in the example.

**Comment by Gryzor** [comment]
Hello! Thank you for your prompt response. I have indeed changed that and it seems to work (I pushed the change to the above repo if you want to check it). Seems like they both perform the same now. Nice :)

One final question, in my xml resources, now Android Studio complains that `transitionSet` and `transitionManager` must be declared. It works, but it's a "red error", is there any workaround this? 

![screen shot 2016-09-14 at 10 20 07 am](https://cloud.githubusercontent.com/assets/15253/18522422/dbe9f03c-7a64-11e6-9e55-c722aaca0637.jpg)

Thanks!

**Comment by andkulikov** [comment]
I don't know how to fix it. Its just a lint check and it knows nothing about the transitionManager in anim folder. Why we use anim here because transitions folder works only starting from kitkat.

I happy to hear that is work the same as framework version for you! It was a purpose to create the library :)
