### ISSUE TITLE
CardView shadow is lost during transition (on Lollipop and newer)

### ISSUE THREAD

**Issue by twyatt** [andkulikov/Transitions-Everywhere#49]
When a CardView is involved in a Slide transition, it will loose it's shadow. This doesn't seem to effect pre-Lollipop (tested on 4.1.1 and 4.3 and CardView kept it's shadow) but on 5.0+ (tested on 5.0 and 6.0) it looses it's shadow.

Forked and branched to help demonstrate the issue:
https://github.com/twyatt/Transitions-Everywhere/tree/demo-cardview-loosing-shadow

Run sample app -> Scene to scene transitions -> Scene 3 -> Scene 2

On pre-Lollipop you'll see the transition as expected, but on Lollipop and newer you'll see the CardView (that holds the TextView) will loose it's shadow during the transition.

...and while I'm here: thanks for this great library! 😄

**Comment by twyatt** [comment]
Upon further investigation, it appears to be a bug in the Android transitions framework? I made a quick project using the native Transitions (not transitions-everywhere) objects and saw the same loss of shadow issue on the CardView. :(

It seems any view with elevation (and therefore shadow) will loose the shadow during a transition.

**Comment by andkulikov** [comment]
Hello. Thank you for reporting! I will investigate more and try to find way to update elevation position as well and report a bug to framework bugtracker.

**Comment by andkulikov** [comment]
I haven't found any workaround for it so I created a bug for android: https://code.google.com/p/android/issues/detail?id=227164
Please star it to have more attention on it.

**Comment by andkulikov** [comment]
The framework issue is fixed on Android 8.0
