### ISSUE TITLE
No animations seen even for example code

### ISSUE THREAD

**Issue by deshant** [andkulikov/Transitions-Everywhere#51]
I followed the article, first added dependency in gradle, Than added following in fragment:
```
ViewGroup transitionContainer = (ViewGroup) rootView.findViewById(R.id.temp_container);
Button tempButton = (Button) transitionContainer.findViewById(R.id.temp_button);
final TextView tempView = (TextView) transitionContainer.findViewById(R.id.temp_text);
TransitionManager.beginDelayedTransition(transitionContainer);
```

Layout file has a android.support.design.widget.CoordinatorLayout parent, in which along with other LinearLayouts I added a LinearLayout to test transition.

`tempView.setVisibility((toggle)? View.VISIBLE : View.GONE);`
above line is working perfectly and the textview is coming and going out of view as expected.

Thing is, there is no animation at all. I tried specifying custom transition too, to no avail.

I am lost, it just wont work, and after searching around, it seems like I am the only one this library hates.
Looking forward to hear about silly mistakes I did, thanks in advance.

P.S. 
Other uninteresting stuff:
Android Studio 2.2.2
buildToolsVersion 23.0.2
compileSdkVersion 24
minSdkVersion 16
library version 1.7.0
Testing device: Xperia Z4 (Android 6.0.1)

**Comment by andkulikov** [comment]
Hi.

You have to call line
TransitionManager.beginDelayedTransition(transitionContainer);
right before every change you want animate, like:
tempView.setVisibility((toggle)? View.VISIBLE : View.GONE);
not only once somewhere in constructor

**Comment by deshant** [comment]
Wow! Thanks!
I knew I was doing a ridiculously silly mistake, so no surprises. Thanks again!

**Comment by deshant** [comment]
> You have to call line
TransitionManager.beginDelayedTransition(transitionContainer);
right before every change you want animate

Consider this, I have an ImageView initially hidden (View.GONE), when splash activity launches, I am calling delayed transition function just before setting visibility View.VISIBLE . 

I have a few similar situations, when views are changing automatically without user clicking some buttons, after layout comes into view, and animations are not visible.

In general, how can we add animation to a view which changes according to some a sync tasks?

Sorry for causing any trouble :/
