### ISSUE TITLE
[Question] Transition between several layouts

### ISSUE THREAD

**Issue by sough** [andkulikov/Transitions-Everywhere#54]
Hello, u don't have example of such behaviour - I want to move clone of some deeply layouted image outside the screen, how can I do that? Now all transitions take place inside parent layout only
Thanks in advance

**Comment by andkulikov** [comment]
Hey!

I could even show two variants how to achieve it:
https://gist.github.com/andkulikov/de892e736aadafd92293cb521098b70e
and
https://gist.github.com/andkulikov/18cf1f88e5c3f3f2ad139444ace487e3

Feel free to ask you have any further questions.


_PS: привет Казахстану. а я в Кустанае родился_
