### ISSUE TITLE
[Question] unit tests for Transition / Animation test

### ISSUE THREAD

**Issue by dush999** [andkulikov/Transitions-Everywhere#55]
Anyone has done unit testing (with Robolectric 3.2.2 ) for Transition/ Animation views. Any example code / reference links would greatly appreciated. 
Thanks in advance

**Comment by andkulikov** [comment]
I didn't try. But transitions its just animators. Please try to find any info how to test screens with animations

**Comment by dush999** [comment]
@andkulikov Thanks !
