### ISSUE TITLE
Can't use Transitions-Everywhere error with R.styleable

### ISSUE THREAD

**Issue by ruzerix** [andkulikov/Transitions-Everywhere#61]
Hello,
Thank you for your library, but I have a problem when try to test it.
First, I just start to use Android studio (I'm android beginner) and want to try you transition library.
Then i got this error.
1. In your transitionseverywhere/extra/Scale they can't find R.styleable
2. In your example AutoTransitionSample they can't find R.layout.fragment_autotransition (i already copy layout file to res/layout folder)

May you guide me to solve this issue.
Thank you very much.

**Comment by andkulikov** [comment]
Hello,

Its hard to say something when I can't see what are you doing exactly. 
To try sample you don't need to copy it file by file. Just check out whole project from git.

Probably you forgot to copy something

**Comment by ruzerix** [comment]
Hi,

At last, I can run it by
1. use com.transitionseverywhere.R for transitionseverywhere/extra/Scale
2. add import my.java.com.path.R for R.layout.*
 and something that i miss.

So thank you
