### ISSUE TITLE
CHANGE_BEHAVIOR_OUT_IN and CHANGE_BEHAVIOR_IN paramerters for new ChangeText().setChangeBehavior() changes color from original

### ISSUE THREAD

**Issue by droidluv** [andkulikov/Transitions-Everywhere#67]
I have textview which has a text that changes on click its color value is #FF1D9ECB, on click I call

TransitionManager.beginDelayedTransition(container, new ChangeText().setChangeBehavior(ChangeText.CHANGE_BEHAVIOR_OUT_IN));

The animation of the text fading out the old text and fading in the new text happens nicely but the original blue color(hex value given above) changes to become green color.

Why does this happen? it doesnt happen for CHANGE_BEHAVIOUR_OUT which I am using for now but I want the behaviour of CHANGE_BEHAVIOR_OUT_IN without the color change.

I am using version 1.7.3 of the library

**Comment by andkulikov** [comment]
Hi,
It was indeed the bug. I fixed it and released in 1.7.4. Thanks
I also created a framework bug for that typo in the code:
https://issuetracker.google.com/issues/62422305
