### ISSUE TITLE
Help on formatting text after transition

### ISSUE THREAD

**Issue by jonasrotilli** [andkulikov/Transitions-Everywhere#69]
When changing the text of a TextView using the transition, the layout characteristics (example textAppearance) are lost.
Is there any way for the transition to keep the features and animate only the text exchange?

I used the code 

TransitionManager.beginDelayedTransition(view,
                        new ChangeText().setChangeBehavior(ChangeText.CHANGE_BEHAVIOR_OUT_IN));
                textView.setText("Test");

**Comment by andkulikov** [comment]
Hello. What exactly do you lose? Color? can you show me a more detailed example? 
Thanks

**Comment by andkulikov** [comment]
ChangeText is animating only text color. If you will have some more details please comment here
