### ISSUE TITLE
How to get callback while path motion animation is happening

### ISSUE THREAD

**Issue by suresh777** [andkulikov/Transitions-Everywhere#73]
I am using path motion animation,while moving image from one place to another place in some path i want to change images in between

**Comment by andkulikov** [comment]
Hi,
Looks like you don't really need to have a callback. As I understood you want to combine view moving by ChangeBounds with images change(like with crossfade?). So you can create a new transition to animate images and add it into TransitionSet together with ChangeBounds. How do you can animate images change? Probably in your custom Transition you can use LayerDrawable to wrap two images inside and than return animator which will animate alphas of your layers.
