### ISSUE TITLE
Overlay other layouts

### ISSUE THREAD

**Issue by afiqiqmal** [andkulikov/Transitions-Everywhere#76]
I have a conditions where need to show and hide several views. it display when button clicked. The problem is, i need to click several times to make it work.. how to fix this?

```
TransitionManager.beginDelayedTransition(form_ll);
switch (id) {
      case "MC":
           attachment.setVisibility(View.VISIBLE);
           spinnerModeRl.setVisibility(View.GONE);
           spinnerHdRl.setVisibility(View.GONE);
           break;
      case "WR":
            attachment.setVisibility(View.GONE);
            spinnerModeRl.setVisibility(View.GONE);
            spinnerHdRl.setVisibility(View.GONE);
            break;
      default:
            spinnerModeRl.setVisibility(View.VISIBLE);
            spinnerHdRl.setVisibility(View.GONE);
            attachment.setVisibility(View.GONE);
            break;
}
```

It seems like the views is overlay other view, on first click..

![screenshot_2017-12-10-09-33-38-425_com iteractive bepunct](https://user-images.githubusercontent.com/9051312/33801186-c103f35c-dd8d-11e7-9944-41828bbdb38e.png)

The second click, it back to original place

![screenshot_2017-12-10-09-50-58-172_com iteractive bepunct](https://user-images.githubusercontent.com/9051312/33801245-f74a7ee8-dd8f-11e7-939e-d8319855021d.png)

is it what im doing it wrong or its a bug? Please advise.

**Comment by andkulikov** [comment]
@afiqiqmal so have you found the reason?
