### ISSUE TITLE
Transitions change duration 

### ISSUE THREAD

**Issue by medozeus** [andkulikov/Transitions-Everywhere#77]

**Comment by andkulikov** [comment]
Hi, could your provide some information please?

**Comment by medozeus** [comment]
the duration of animation so slow i want to Decrease the duration of animtaion

**Comment by andkulikov** [comment]
please check samples or read an article https://medium.com/@andkulikov/animate-all-the-things-transitions-in-android-914af5477d50 chapter "What else we can do"
