### ISSUE TITLE
a flickering when changing state of button.

### ISSUE THREAD

**Issue by manafzar** [andkulikov/Transitions-Everywhere#78]
When doing a simple sequential fade-in & fade out for two buttons for a moment text changes to something weird. i have tried support library too same result.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3052047/34916455-e57fa178-f94d-11e7-8b38-3218f318394f.gif)

**Comment by andkulikov** [comment]
there is ChangeText transition, which in one of the modes can keep the previous text for the time of transition. btw, can you show the code?

**Comment by manafzar** [comment]
Thanks for replay. Here is the code:
```
TransitionManager.beginDelayedTransition((ViewGroup) binding.getRoot());
binding.buttonDestination.setVisibility(View.GONE);
binding.buttonRequest.setVisibility(View.VISIBLE);
```
So is there any solution for this?

**Comment by andkulikov** [comment]
if you have two buttons why do you change text on the buttons? are you using data binding which can do this for you?
what is "S F" from your gif?

but you can try this variant:

   ```
     TransitionSet transitionSet =
            new TransitionSet()
                .setOrdering(TransitionSet.ORDERING_SEQUENTIAL)
                .addTransition(
                    new TransitionSet()
                        .addTransition(new Fade(Fade.OUT))
                        .addTransition(new ChangeText())
                ).addTransition(new Fade(Fade.IN))
            ;
        TransitionManager.beginDelayedTransition((ViewGroup) binding.getRoot(), transitionSet);
```

**Comment by manafzar** [comment]
Well that's what is weird for me too that where this S F thing is coming because i have not set text to that at all in my code. (I'm sure checked this like 10 times :|). And also i didn't changed the text at all i have only made first button hidden and second one visible but it changes the text automatically for a second and i don't know why. Maybe it has something to do with databinding. Using your code it still happens too.

**Comment by andkulikov** [comment]
yeah, data binding should the root of it. could you please debug calls for TextView.setText

**Comment by manafzar** [comment]
Thanks again for response. But i did that and breakpoint doesn't get reached! (breakpoint working properly has been checked using manual test.)

**Comment by dev-JE02** [comment]
I don't think that is an "F". I believe that us an E. I also get the same issue when starting the transition. The text also becomes out of place after transition

**Comment by andkulikov** [comment]
so the text for a view was changed to "select ..." and at the same time the view was hidden via view.setVisibility(gone). why do you change text of view you are going to hide? probably here it was changed automatically by data binding which is wrong. @dev-JE02 you also use databinding?
