### ISSUE TITLE
Scene class is final ??

### ISSUE THREAD

**Issue by LLudoDev** [andkulikov/Transitions-Everywhere#79]
Hi, why the Scene class is final ? I am working on an technical architecture based on the Scene class and i need to override it.
Then, is the final keyword optionnal are not ?

**Comment by andkulikov** [comment]
Hi. My library is just a backport of Transitions from Android Framework. There Scene class is final, that why it is final here as well. Why do you need to override it, why can't you use a composition there?

**Comment by LLudoDev** [comment]
With the android.support.transition.Scene i could override the Scene that’s why i asked that.
Ok, then i will still use the Scene object as a composition.
Thx !

**Comment by andkulikov** [comment]
I have no idea why do they removed final in support lib but I still suggest to not override it
