### ISSUE TITLE
Transition removeTarget is not working when using constraintLayout animations

### ISSUE THREAD

**Issue by dev-JE02** [andkulikov/Transitions-Everywhere#80]
I tried using `removeTarget(View)` and `removeTarget(int viewId)` but it is still animated when I apply a new constraintSet to my constraintLayout

**Comment by andkulikov** [comment]
use excludeTarget. removeTarget is just a pair action for addTarget, to cancel it;

**Comment by dev-JE02** [comment]
When I use excludeTarget the view suddenly disappears on start of the transition.

Also do you know why the text gets distorted why the views are animating bounds and positions?

**Comment by andkulikov** [comment]
suddenly disappears == not animating, as you excluded it from animation. you wanted it? 
"views are animating bounds and positions" because ChangeBounds transition animates bounds and position. it is not animating text

**Comment by dev-JE02** [comment]
Ohhh. Is there a way to make it stay the way it is? Not disappearing, not animating, just stay on screen maintaining its bounds and postiion.

For the text I was referring to the same issue as in this issue: https://github.com/andkulikov/Transitions-Everywhere/issues/78

**Comment by andkulikov** [comment]
Transitions is about animating the change. from previous state to the next state. as your view disappears it means the view is disappeared int the next state. so if it will just stay on the same position visible how it will then became disappeared?

**Comment by andkulikov** [comment]
if you want this view to stay visible where it was just don't change the visibility or layout params of it
