### ISSUE TITLE
Cannot open sample app in Android studio 2.3 

### ISSUE THREAD

**Issue by buptfarmer** [andkulikov/Transitions-Everywhere#81]
Hello andkulikov,
It seems that the sample app cannot be open in Android studio 2.3 , with 
```
Error:(4, 0) Gradle DSL method not found: 'google()'
Possible causes:<ul><li>The project 'sample' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 2.3.3 and sync project</a></li><li>The project 'sample' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>
```
After I googled a while, found that I need to use Android Studio 3.0+ gradle 4.x to compile the sample app, and it seems quite inconvenient for some developer who have not switch to Android Studio 3.0.
If you need another structure to support Android Studio 2.3, I would be glad to to that. 

Thanks
Chanson

**Comment by andkulikov** [comment]
Hi,
You can easily change plugin versions in Gradle files if you need it in
your downloaded copy, or you can fork it and change. I think majority of
other library users are using up to date versions of studio and plugin so
it would be easier for them to have it updated. So I am not going to change
defauld sample app code for it.
Thanks

**Comment by buptfarmer** [comment]
ok， thanks。
