### ISSUE TITLE
Got error in new Rotate() 

### ISSUE THREAD

**Issue by SimonPeter1909** [andkulikov/Transitions-Everywhere#84]
I was trying to implement Rotation to my imageview.

`TransitionManager.beginDelayedTransition(dashboardRL, new Rotate());`

but i got the wrong 2nd argument type.

```
Wrong 2nd argument type. Found: 'com.transitionseverywhere.Rotate', required: 'android.transition.Transition' less... 

beginDelayedTransition
(ViewGroup,
android.transition.Transition)
in TransitionManager cannot be applied
to
(RelativeLayout,
com.transitionseverywhere.Rotate)
```

**Comment by andkulikov** [comment]
you imported wrong TransitionManager. please check import. it should be com.transitionseverywhere.TransitionManager
