### ISSUE TITLE
Explode Mode In

### ISSUE THREAD

**Issue by sagarpatel288** [andkulikov/Transitions-Everywhere#85]
Explode mode _IN_ seems not working properly or can we have an example of it?
Regards,
Sagar

**Comment by andkulikov** [comment]
Mode IN is what will be performed when you had no views and then added new views into a transition container. 
I would instead ask you to provide an example when you think it is not working so I will be able to point out where is the mistake. Can you do it?

**Comment by andkulikov** [comment]
Slide can be used for moving all the items into on of the sides(like top or left/bottom corner), but you can't use it for moving into centre of the screen as being finished in the centre of the screen hard to be considered as "disappeared"
