### ISSUE TITLE
Is there any way to rotate menu item in the bottomNavigationView?

### ISSUE THREAD

**Issue by SimonPeter1909** [andkulikov/Transitions-Everywhere#86]
I have a bottomNavigationView and I have to load more menu items when I press the more icon in the bottoNavigationView. So If the More menu item rotates it will look good...

**Comment by andkulikov** [comment]
Hi. I don't know how updating menu items is implemented in bottomNavigationView, never used this widget. But I don't think it is a task for Transitions anyway. So you have more icon before and after this change? To start animation you need ability to get view itself in some way, not menu item. Please check do they provide such api, if you have view you can start animator on it.
