### ISSUE TITLE
Transitions Everywhere uses Reflection that may crash on P+ devices

### ISSUE THREAD

**Issue by TealOcean** [andkulikov/Transitions-Everywhere#90]
See: https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

It appears ReflectionUtils is the primary problem, but it would appear the usages of reflection may become a problem with P.

There are published lists of APIs that will break on P (https://android.googlesource.com/platform/prebuilts/runtime/+/master/appcompat).

**Comment by TealOcean** [comment]
Cool, so just to clarify, is the guidance to use the support library variant of transitions once the next release goes out (The Android X one)?

**Comment by andkulikov** [comment]
Please check out the main README file. I released version 2.0.0 of Transitions-Everywhere based on AndroidX transitions and provided a migration guide.
