### ISSUE TITLE
package/symbol R does not exist

### ISSUE THREAD

**Issue by CodEddy** [andkulikov/Transitions-Everywhere#91]
I'm new to this, sorry if I do/ask anything that I shouldn't.
When I imported the library I got:

`import com.transitionseverywhere.R; java package R does not exist`

What am I missing?

**Comment by andkulikov** [comment]
Hi. 
Did you copy library files into your project?
What exactly you are trying to solve, why don't you just add library as a dependency into your gradle script?

**Comment by CodEddy** [comment]
Yes, I copied all the library files, I tried various times. I tried to add it as a module too but it didn't work. How do I exactly add it as a dependency as you say?

**Comment by andkulikov** [comment]
to add a new library add it's dependency into a build.gradle file like this
dependencies {
    compile "com.andkulikov:transitionseverywhere:1.8.1"
}
