### ISSUE TITLE
Change Text is opening the keyboard

### ISSUE THREAD

**Issue by quensh93** [andkulikov/Transitions-Everywhere#92]
hi
i'm using below code to change text :

`@BindingAdapter("customText")
    public static void setCustomText(TextView view, String text){
        TransitionManager.beginDelayedTransition(((ViewGroup) view.getParent()),
                new ChangeText().setChangeBehavior(ChangeText.CHANGE_BEHAVIOR_OUT_IN));
        view.setText(text);
    }`

also i'm using `android:focusableInTouchMode="true"` in my container
but after calling customText, keyboard is opening if i have a edittext in the same container! but if i put the textview inside another container it is working fine

**Comment by andkulikov** [comment]
Are you sure it happens only because of beginDelayedTransition? ChangeText only animates text color and then call setText. Probably it is some limitation of android:focusableInTouchMode, I am not an expert about it. Feel free to recheck and contribute a fix if you sure it caused by ChangeText
