### ISSUE TITLE
Wrong minSdkVersion?

### ISSUE THREAD

**Issue by giles-payne-d** [andkulikov/Transitions-Everywhere#95]
I am trying out 2.0.0-alpha02
According to the README.md and the build.gradle the minSdkVersion is 14, but Android Studio is telling me its 16 (which is too high for my project). Can you confirm which is correct?

**Comment by andkulikov** [comment]
Hm, I double checked and it should be 14. 14 Is min sdk for AndroidX libraries. 14 also is a min sdk for transitions-everywhere. Also my sample which is a part of this repo is having 14 as min sdk and it compiles ok. Maybe you added some other libraries as well? 
Maybe MergedManifest feature from Android Studio will help you understand where did you get 16
https://www.reddit.com/r/androiddev/comments/6zdp5m/til_theres_merged_manifest_tab_in_android_studio/

**Comment by giles-payne-d** [comment]
Sorry - my bad - it was another library that was causing the issue.
Closing this.
